module EmailParser
  module SignaturePatterns
    # http://www.writeexpress.com/letterclosings.html
    CLOSING_PATTERNS = [
      'Adios',
      'All best wishes',
      'All best always',
      'All best, always',
      'Always in my thoughts',
      'As always with affection',
      'As always, with affection',
      'As usual',
      'As ever',
      'Be good',
      'Be well',
      'Best',
      'Best Regards',
      'Best wishes for your future',
      'Best Wishes',
      'Bye for now',
      'Cheerio',
      'Cheers',
      'Chill',
      'Cordially',
      'Earnestly',
      'Enjoy',
      'Enthusiastically',
      'Forever yours',
      'God bless',
      'God be with you',
      'Godspeed',
      'Good wishes always',
      'Good wishes, always',
      'Goodbye',
      'Gotta boogie',
      'Grace and peace',
      'Have fun',
      'Health & Happiness',
      'Health and Happiness',
      'Hope to hear from ya soon',
      'Hope all is well',
      'I look forward to hearing from you soon',
      'I hope to receive news from you soon',
      'I\'ll be thinking of you',
      'Just to keep in touch with you',
      'Keep the faith',
      'Keep smiling',
      'Kind regards',
      'Kind Regards',
      'Kind thoughts',
      'Later Vader!',
      'Later',
      'Later alligator',
      'Later',
      'LET\'S GO',
      'Looking forward to seeing you again',
      'Lots of love',
      'Love',
      'Many thanks',
      'May the horse be with you',
      'May the Force be with you',
      'May I always live to serve you and your crown',
      'Miss ya',
      'More later',
      'More shortly',
      'Most sincerely',
      'Onward and upward',
      'Over & Out',
      'Over and out',
      'Peace, Love & Happiness',
      'Peace be with you',
      'Peace & Love',
      'Peace out',
      'Peace and Blessings',
      'Peace',
      'Prayerfully',
      'Regards',
      'Respectfully yours with sincere gratitude',
      'Rock on',
      'Saludos',
      'Season\'s blessings',
      'See ya',
      'Seeya',
      'Sincerely',
      'Sincerely yours',
      'Smell ya later',
      'SMILE!',
      'Smiles',
      'Ta ta',
      'Take care',
      'Take good care',
      'Take it easy',
      'Talk to you later',
      'Thank you',
      'Thank you for your time and consideration',
      'Thank you for yor kindness and consideration',
      'Thanks',
      'Thinking the best for you',
      'Til then, my beloved',
      'Till we meet again',
      'Toodles',
      'Truly',
      'ttyl',
      'Until we meet again',
      'Until next time',
      'Very truly yours',
      'Waiting for you',
      'Warm regards',
      'Warmest greetings to all',
      'Warmest Regards',
      'Wishing you all the best of everything',
      'Wishing you the best',
      'Wishing you a safe journey',
      'With confidence',
      'With the highest esteem, I am a friend of virtue and the people',
      'With kind affection',
      'With kindest personal regards',
      'With warmth',
      'With gratitude',
      'With all best wishes',
      'With love',
      'With all good wishes',
      'Yearning for you',
      'You\'re in my prayers',
      'You\'re in my thoughts',
      'Your friend',
      'Yours truly',
      'Yours faithfully',
      'Yours sincerely',
      'Yours regardless',
      'Yours \'til the cat meows',
      'Yours most sincerely',
      'Yours always',
      'Yours ever',
      'Yours respectfully',
      'Yours'
    ].freeze

    PHONE_CLOSING_PATTERNS = [
      '^sent from .*'
    ].freeze

    PHONE_CLOSING_RE = Regexp.new(
      "(#{PHONE_CLOSING_PATTERNS.join('|')}|--)",
      Regexp::IGNORECASE
    ).freeze

    CLOSING_RE = Regexp.new(
      "(#{CLOSING_PATTERNS.join('|')}|--)",
      Regexp::IGNORECASE
    ).freeze
  end
end
